language: java
jdk:
- openjdk7
- oraclejdk7
- oraclejdk8
notifications:
  slack:
    secure: tZE8o8G2rKWSFVPr+9MIkUI/jvdsL0PiqVE9W3dincegZbUw6nJmwh1QF8NIU5Jc7HgPBAts+25e8CkRGS50/6sFmTjsXgEbIEkm7hCs3gdVOFDpNwyWPkbCN8PBQFeBITctfR1PM0tXlOk2QqrJLBmeESG0R37C9sJ3Dlm6Qv0hfM0pgAfLfAr4mX0fQI9a0i7OFuUzL2edgmSPW4bfWBau9E3dIeis3zgJXjim8YLcuM+gfQTRFA6oPbB2YdkwI2t1iKz3dwYcujMv4gdIxdUTgXwbNI+kgHkuOtYopt6s7d5jcmYgXQOtJEmesLUNOKqjWwNoa2YfUuFjDtBVXb3mmO3OfmmEySqK9GeRlsK2ouHxyYR2mJbeuofogqhpr/MLMLhyWYUPN9KTXRgTl5v0nk9GmtTOdq55sv2xcyt1zWf8Eved0uQsAzXP700X7iQ8W742wOT7AUNlusGteY6UTVM3cOcEwiDlHNAjf9se0G2nfqulVn6aEhxIgRbpobKD6YUU5HlWD41ca2QAcfT6wKZWdD9+g3BHPFOGjQL3HOfK/vG0qAOeCiJa8rY1Q8lrWo7wNtXOlFYXxMHV1I9gdpoJWudCZZzkK9Ee+DyHxf7QOg+oAKgxUDK8Ba7/bcBaYj5y+RuU83nWxEuM4FYVMsO4YIFbyujfpz8j7GM=
